seed: 42
output_dir: ./out/ttslearn

preprocess:
  wav_dir: /disk/fs1/Corpus/JSUT/jsut_ver1.1/basic5000/wav
  label_dir: /disk/fs1/Corpus/JSUT/jsut-label/labels/basic5000
  output_dir: ../dataset/ttslearn
  orig_sr: 48000
  new_sr: 24000
  spec: ${spec}
  mel: ${mel}

spec:
  n_fft: 1024
  win_length: 1024
  hop_length: 256
  center: false

mel:
  sample_rate: ${preprocess.new_sr}
  n_fft: ${spec.n_fft}
  win_length: ${spec.win_length}
  hop_length: ${spec.hop_length}
  f_min: 0
  f_max: 8000
  n_mels: 80
  center: ${spec.center}

train:
  batch_size: 16
  num_epochs: 500
  save_interval: 250

data:
  mode: all
  data_dir: ../dataset/pp_add
  valid_size: 100

model:
  n_mel: ${mel.n_mels}
  n_spec: 513
  channels: 192
  segment_size: 8192
  mel_segment: 32

  embedding:
    n_phoneme: 52
    channels: ${model.channels}

  encoder:
    channels: ${model.channels}
    n_heads: 2
    kernel_size: 3
    dropout: 0.1
    n_layers: 6
    window_size: 4

  va:
    in_channels: ${model.channels}
    channels: 256
    dropout: 0.5

  flow:
    channels: ${model.channels}
    kernel_size: 5
    dilation_rate: 1
    n_layers: 4
    n_flows: 4

  posterior_encoder:
    in_channels: ${model.n_spec}
    out_channels: ${model.channels}
    kernel_size: 5
    dilation_rate: 1
    n_layers: 16

  signal_generator:
    stats_dir: ${data.data_dir}
    sr: ${preprocess.new_sr}
    frame_shift: ${spec.hop_length}

  generator:
    initial_channel: ${model.channels}
    resblock_kernel_sizes: [3, 7, 11]
    resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
    upsample_rates: [8, 8, 2, 2]
    upsample_initial_channel: 512
    upsample_kernel_sizes: [16, 16, 4, 4]

optimizer:
  lr: 0.0002
  betas: [0.8, 0.99]

scheduler:
  gamma: 0.999875

